apiVersion: apps/v1
kind: Deployment
metadata:
  name: far-demo-far-2-cel
  namespace: default
  labels:
    app.kubernetes.io/instance: far-demo
    app.kubernetes.io/name: far-demo-far-2-cel
    helm.sh/chart: far-2-cel-0.1.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: far-demo
      app.kubernetes.io/name: far-demo-far-2-cel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: far-demo
        app.kubernetes.io/name: far-demo-far-2-cel
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        helm.sh/chart: far-2-cel-0.1.0
    spec:
      serviceAccountName: far-2-cel-sa
      containers:
        - name: far-2-cel
          image: gcr.io/striped-temple-485610-b7/github.com/agorbach/test2025
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: far-demo-far-2-cel
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app.kubernetes.io/instance: far-demo
    app.kubernetes.io/name: far-demo-far-2-cel
    helm.sh/chart: far-2-cel-0.1.0
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/instance: far-demo
    app.kubernetes.io/name: far-demo-far-2-cel
